// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models;

[Table("Employee")]
public partial class Employee
{
    [Key]
    public int EmployeeId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string EmployeeName { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string EmployeeDesignation { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? EmployeeSalary { get; set; }

    public int? StateId { get; set; }

    public int? DistrictId { get; set; }

    public int? CityId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string EmployeeAddress { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string EmployeeMobileNo { get; set; }

    [ForeignKey("CityId")]
    [InverseProperty("Employees")]
    public virtual City City { get; set; }

    [ForeignKey("DistrictId")]
    [InverseProperty("Employees")]
    public virtual District District { get; set; }

    [ForeignKey("StateId")]
    [InverseProperty("Employees")]
    public virtual State State { get; set; }
}