// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models;

[Table("State")]
public partial class State
{
    [Key]
    public int StateId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string StateName { get; set; }

    [InverseProperty("State")]
    public virtual ICollection<District> Districts { get; set; } = new List<District>();

    [InverseProperty("State")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}