// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Employee_API.Models;

[Table("City")]
public partial class City
{
    [Key]
    public int CityId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string CityName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string CityDesc { get; set; }

    public int? DistrictId { get; set; }

    [ForeignKey("DistrictId")]
    [InverseProperty("Cities")]
    public virtual District District { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}