// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Employee_API.Models;

[Table("District")]
public partial class District
{
    [Key]
    public int DistrictId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string DistrictName { get; set; }

    public int? StateId { get; set; }

    [InverseProperty("District")]
    public virtual ICollection<City> Cities { get; set; } = new List<City>();

    [InverseProperty("District")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    [ForeignKey("StateId")]
    [InverseProperty("Districts")]
    public virtual State State { get; set; }
}